# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0384b9ccfae8a92fa8ec545a40d05e0ea9e3d76a282389f6e8836223b6720aa025b861f4e4f8f3a1a463539e9221f1195db79e901ab439e2f88dcb20158c2a52

test:
  secret_key_base: 32cf0e50fbd34e03901d066be57a43d5238bd576e26f75273bb81f462bdd8aa5f9c1c2135a4e3d75905ae9461b60ae521378b78ba4b8271cff5528273a9ae517

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
